"""
Content-based bot filtering, submission-statement stripping and username masking.

Added to the pipeline after the corpus v1 freeze, when exact-duplicate detection
revealed that the author-based bot filter in 02_preprocess.py left a residue of
automated content. A raw-data audit established the mechanism: all of the
surviving rows had populated authorName fields, but none matched the eight-account
KNOWN_BOTS set. The residue was caused by INCOMPLETE ACCOUNT-LIST COVERAGE, not by
missing author metadata. A content-based filter is the appropriate complement
because it does not depend on anticipating the account list.

Pipeline position
-----------------
    remove_bot_content()        immediately after clean_body is computed
    strip_submission_wrapper()  after remove_bot_content(), BEFORE the word floor
    resolve_relay_duplicates()  after strip_submission_wrapper()
    mask_usernames()            after resolve_relay_duplicates()

All four require clean_body and must therefore run after it exists. They cannot be
placed next to the author-based bot filter, which runs earlier.

The position of strip_submission_wrapper() relative to the word floor is
load-bearing: it shortens comment text, so the floor must be applied to the
stripped text. Running it after the floor would retain comments whose length came
entirely from automated wrapper text.

The row-removal and wrapper-stripping operations are monotone with respect to
corpus membership. Username masking is a de-identification substitution; in the
audited v2.2 run it changed no word counts. Exact membership relationships are
established by the id-set comparisons in verify_v2_membership.py rather than
assumed from operation ordering; that verifier also records the single expected
difference caused by the expanded author-based bot filter.

Author: Arnaud Dorasamy (24916660)
"""

from __future__ import annotations

import re

import pandas as pd


# --------------------------------------------------------------------------
# Pattern 1 — automated boilerplate, removed outright
# --------------------------------------------------------------------------
# Matched anywhere in the comment. Each alternative identifies text that is
# generated by AutoModerator or a utility bot, or posted by a moderator in an
# administrative capacity. None of it is user discourse.

BOT_BOILERPLATE = re.compile(
    r"(?:"
    r"^welcome to /?r/"                                    # subreddit welcome sticky
    r"|\bi(?:'m|m| am) a bot\b"                            # bot self-identification                                    
    r"|action was performed automatically"                 # AutoModerator footer
    r"|\bbeep boop\b"                                      # utility bot preamble
    r"|thank you for your (?:comment|contribution)"        # removal notice
    r".{0,40}(?:has been|was) removed"
    r"|we appreciate you wanting to contribute to /?r/"    # participation notice
    r")",
    re.IGNORECASE,
)

MOD_ADMINISTRATIVE = re.compile(
    r"^(?:"
    r"we require that posters seed their post"             # rule explainer
    r"|hello,? everyone!? want to help improve this community"  # mod recruitment
    r")",
    re.IGNORECASE,
)


# --------------------------------------------------------------------------
# Pattern 2 — submission-statement wrapper, stripped in place
# --------------------------------------------------------------------------
# r/Futurology requires posters to supply a "submission statement". AutoModerator
# relays it into the comment stream wrapped in generated header and footer text.
# The wrapper is automated; the body between the wrappers is written by the poster
# and is retained.
#
# One poster prefixes every statement with a fixed template about the editing
# mechanism, separated from their actual statement by a run of underscores.
# The template carries no content and is removed; the underscore run provides
# an explicit boundary rather than an inferred one.

RELAY_HEADER = re.compile(
    r"^the following submission statement was provided by\s*/?u/[\w\-]+\s*:\s*-{2,}\s*",
    re.IGNORECASE,
)

RELAY_FOOTER = re.compile(
    r"\s*-{2,}\s*please reply to op'?s comment here:?\s*.*$",
    re.IGNORECASE | re.DOTALL,
)

POSTER_TEMPLATE = re.compile(
    r"submission statement from op\.?\s*note:\s*this submission statement\s*\"?locks in\"?"
    r".*?needs must\."
    r"(?:\s*there is often required additional grammatical editing"
    r"(?:\s*and additional added detail)?\.)?",
    re.IGNORECASE | re.DOTALL,
)

SEPARATOR_RULE = re.compile(r"_{5,}")

STATEMENT_LABEL = re.compile(
    r"^\s*(?:submission statement[.:]?(?:\s*from op[.:]?)?|seed statement:)\s*",
    re.IGNORECASE,
)

SUBMISSION_STATEMENT = re.compile(
    r"^(?:the following submission statement was provided by|submission statement)",
    re.IGNORECASE,
)


# --------------------------------------------------------------------------
# Pattern 3 -- in-text username mentions
# --------------------------------------------------------------------------
# Reddit renders a user mention as /u/name or u/name. The leading lookbehind
# prevents matches inside ordinary words ("ou/being" is not a mention). Mentions
# are replaced with a placeholder rather than deleted, so the discourse fact that
# somebody was addressed survives while the identifier does not. The replacement
# is a single token, so no word count changes and no comment can cross the floor.

USERNAME_MENTION = re.compile(r"(?<![A-Za-z0-9])/?u/[A-Za-z0-9_\-]{3,20}\b")
USERNAME_PLACEHOLDER = "/u/[user]"


def remove_bot_content(
    df: pd.DataFrame,
    body_col: str = "clean_body",
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Drop rows matching automated-boilerplate or moderator-administrative patterns.

    Returns (retained, removed). Returning the removed frame makes the exclusions
    inspectable and allows callers to report the number removed without relying on
    a curated list of comment ids.
    """
    body = df[body_col].fillna("")

    is_bot = body.str.contains(
        BOT_BOILERPLATE,
        na=False,
    )

    is_mod = body.str.match(
        MOD_ADMINISTRATIVE,
        na=False,
    )

    drop = is_bot | is_mod

    removed = df[drop].copy()

    removed["filter_reason"] = [
        "mod_administrative" if m else "bot_boilerplate"
        for m in is_mod[drop]
    ]

    return df[~drop].copy(), removed


def _strip_one(text: str) -> str:
    """Remove automated wrapper text from a single submission-statement comment."""
    text = RELAY_HEADER.sub("", text)
    text = RELAY_FOOTER.sub("", text)
    text = POSTER_TEMPLATE.sub("", text)
    text = SEPARATOR_RULE.sub(" ", text)
    text = STATEMENT_LABEL.sub("", text)

    return re.sub(
        r"\s+",
        " ",
        text,
    ).strip(" .-")


def strip_submission_wrapper(
    df: pd.DataFrame,
    body_col: str = "clean_body",
    wordcount_col: str = "clean_wordcount",
) -> pd.DataFrame:
    """Strip automated wrapper text in place and recompute the word count.

    Adds two columns so that every modification is traceable:
      body_stripped   True where wrapper text was removed
      wrapper_source  'relay' where the wrapper was the AutoModerator relay,
                      'label' where only a self-applied statement label was
                      removed, otherwise None

    wrapper_source is required by resolve_relay_duplicates(), which cannot
    distinguish a relayed copy from the poster's own copy once both have been
    stripped to identical text.

    NOTE: when called before `wordcount_col` exists, this creates that column
    populated only for modified rows, with NaN elsewhere. Harmless in the current
    pipeline because the caller recomputes the entire clean_wordcount column before
    applying the word floor. If that recompute is ever moved, this becomes a silent
    partial-population bug.

    Must be called BEFORE the word floor is applied.
    """
    df = df.copy()

    if "body_stripped" not in df.columns:
        df["body_stripped"] = False

    if "wrapper_source" not in df.columns:
        df["wrapper_source"] = None

    body = df[body_col].fillna("")

    target = body.str.match(
        SUBMISSION_STATEMENT,
        na=False,
    )

    is_relay = body.str.match(
        RELAY_HEADER,
        na=False,
    )

    stripped = body[target].map(
        _strip_one
    )

    changed = stripped.index[
        stripped != body[target]
    ]

    df.loc[
        changed,
        body_col,
    ] = stripped[changed]

    df.loc[
        changed,
        "body_stripped",
    ] = True

    df.loc[
        changed,
        wordcount_col,
    ] = (
        stripped[changed]
        .str.split()
        .str.len()
    )

    df.loc[
        changed,
        "wrapper_source",
    ] = [
        "relay" if is_relay.loc[i] else "label"
        for i in changed
    ]

    return df


def resolve_relay_duplicates(
    df: pd.DataFrame,
    body_col: str = "clean_body",
    thread_col: str = "parsedPostId",
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Drop AutoModerator relay copies of comments the poster also posted directly.

    r/Futurology's AutoModerator relays a poster's submission statement into the
    comment stream as a separate comment. Where the poster has also posted the
    statement themselves, the corpus holds the same text twice under two comment
    ids. Deduplication by comment id does not catch this, and the wrapper text
    conceals it until strip_submission_wrapper() has run.

    The retained copy is the one the poster posted; the relayed copy is dropped.
    Where a duplicate group within a thread contains only relayed copies, the
    lexicographically smallest comment id is retained, so the rule is total.

    EDGE CASE: where a group contains a relay copy AND more than one non-relay
    copy, only the lexicographically smallest non-relay copy is retained and the
    remaining non-relay copies are dropped with the relay. This did not arise in
    the study corpus, but the behaviour is stated so it is not discovered later.

    Duplicate text spanning different threads is NOT resolved here: that is
    ordinary repetition by different users and is handled, where relevant, by
    the annotation draw rather than by removal from the corpus.

    Must be called AFTER strip_submission_wrapper().

    Returns (retained, removed).
    """
    df = df.copy()
    drop_ids: list = []

    dup_mask = df.duplicated(
        subset=[
            thread_col,
            body_col,
        ],
        keep=False,
    )

    for _, group in df[dup_mask].groupby(
        [
            thread_col,
            body_col,
        ],
        sort=False,
    ):
        if not (
            group.wrapper_source == "relay"
        ).any():
            continue

        non_relay = group[
            group.wrapper_source != "relay"
        ]

        keep_id = (
            non_relay.id.min()
            if len(non_relay)
            else group.id.min()
        )

        drop_ids.extend(
            group.loc[
                group.id != keep_id,
                "id",
            ].tolist()
        )

    removed = df[
        df.id.isin(drop_ids)
    ].copy()

    removed[
        "filter_reason"
    ] = "automod_relay_duplicate"

    return (
        df[
            ~df.id.isin(drop_ids)
        ].copy(),
        removed,
    )


def mask_usernames(
    df: pd.DataFrame,
    body_col: str = "clean_body",
) -> tuple[pd.DataFrame, int]:
    """Replace in-text Reddit username mentions with a placeholder.

    The project's ethics commitment is that usernames do not appear in analysis
    artefacts. Author metadata is excluded at write time, and the submission-wrapper
    strip removes the poster names AutoModerator inserts. In-text mentions of other
    users are the remaining route by which an account name reaches the corpus, and
    they are masked here for consistency with the same commitment.

    The mention is replaced rather than deleted, so the discourse fact that somebody
    was addressed is preserved while the identifier is not. The replacement is a
    single token, so no word count changes and no comment can cross the word floor
    as a result of masking.

    Returns (df, n_rows_modified).
    """
    df = df.copy()

    body = df[
        body_col
    ].fillna("")

    hit = body.str.contains(
        USERNAME_MENTION,
        na=False,
    )

    df.loc[
        hit,
        body_col,
    ] = body[hit].str.replace(
        USERNAME_MENTION,
        USERNAME_PLACEHOLDER,
        regex=True,
    )

    return df, int(hit.sum())


def apply_word_floor(
    df: pd.DataFrame,
    floor: int = 20,
    wordcount_col: str = "clean_wordcount",
) -> pd.DataFrame:
    """Existing pipeline word floor, restated here so callers cannot reorder it
    ahead of strip_submission_wrapper()."""
    return df[
        df[wordcount_col] >= floor
    ].copy()